name: Publish Docker image
on:
  push:
    tags:
      - "v*"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: |
          .ci/tag-from-ref.sh "${GITHUB_REF}"`
      - name: Push to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: praekeltfoundation/contentrepo
          tag: ${{ steps.get_version.outputs.TAG }}
          registry: docker.io
